Jacobi Method
Explored by John Lain

In [32]:
import numpy as np

Our Jacobi Method Algorithm:

In [33]:
def jacobi(A, b, x0, iterations = 50, tol = 0.000001, true = None):
    """
    Solves a system of linear equations using the Jacobi method
    Expected inputs:
    A: nxn matrix
    b: column vector of length n
    x0: initial guess for solution
    tol: error between true and numerical solution
    true: true solution
    """
    count = 0
    x = x0
    d = np.diagonal(A)
    LU = A - np.diag(d)
    n = np.size(b)
    if type(true) == np.ndarray:
        while max(abs(true - x)) > tol:
            count = count + 1
            x = (1/d)*(b - LU@x)
        print(f"Number of iterations = {count}")
        return(x)
    else:
        for i in range(iterations):
            x = (1/d)*(b - LU@x)
        return(x)


When writing this code, ran into a few errors: Creating different scenarios for the method alorithm when we include the true solution in our input lead to some issues, and had to use the code "type(true) == np.ndarray" which was not clear at first. At first, tried to use matrix multiplication when multiplying by d inverse (like is done in the mathmatical algoritm), however, d is stored as an array in our code and because of vectorized nature of numpy, the solution was to just use the normal multiplication operator.

Testing our algorithm (example from HW 3):

In [34]:
L = np.diag(-np.ones(99), -1)
U = np.diag(-np.ones(99), 1)
d = np.diag(3*np.ones(100))
A = L + U + d
b = np.array([2] + [1]*98 + [2])
x = jacobi(A, b, np.zeros(100), tol = 0.000001, true = np.ones(100))
x


Number of iterations = 35


array([0.99999991, 0.99999982, 0.99999974, 0.99999966, 0.99999959,
       0.99999953, 0.99999948, 0.99999943, 0.9999994 , 0.99999937,
       0.99999936, 0.99999934, 0.99999933, 0.99999932, 0.99999932,
       0.99999932, 0.99999932, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999

Algorithm written by GPT 3.5:

In [35]:
def jacobi_GPT(A, b, x0, tol=1e-6, max_iter=1000):
    n = len(b)
    x = np.array(x0, dtype=float)
    x_new = np.zeros_like(x)
    
    for _ in range(max_iter):
        for i in range(n):
            sum_ = np.dot(A[i, :i], x[:i]) + np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - sum_) / A[i, i]
        
        if np.linalg.norm(x_new - x) < tol:
            return x_new
        
        x = np.copy(x_new)
    
    raise ValueError("Jacobi method did not converge within the maximum number of iterations")

Chat gpts code stops the alorithm when the difference between the new value and the last value is less than a certain amount, which is different than our code which uses a set number of iterations (or requires the solution which is helpful for testing)

Testing Chat GPT's code with example from above:

In [36]:
L = np.diag(-np.ones(99), -1)
U = np.diag(-np.ones(99), 1)
d = np.diag(3*np.ones(100))
A = L + U + d
b = np.array([2] + [1]*98 + [2])
x_GPT = jacobi_GPT(A, b, np.zeros(100), tol = 0.000001)
print(x_GPT)
print(max(abs(x_GPT - x)))

[0.99999997 0.99999995 0.99999992 0.9999999  0.99999988 0.99999987
 0.99999985 0.99999984 0.99999983 0.99999982 0.99999981 0.99999981
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.99999981 0.99999981
 0.9999

The GPT 3.5 code produced a result extremely close to the result of our code. Asking Chat GPT to write the code took about 2 minutes, whereas the code we wrote took about an hour with trial and error being required.

Another example from HW3:

In [37]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b = np.array([0, 2, 0])
x = jacobi(A, b, np.zeros(3))
print(x)
x_gpt = jacobi_GPT(A, b, np.zeros(3))
print(x_gpt)

[0.99999997 1.99999994 0.99999997]
[0.99999905 1.99999905 0.99999905]


Both functions produced results which were close to the true solution of [1, 2, 1]