# Jacobi Method Algorithm coded By John Lain

In [1]:
import numpy as np
def jacobi(A, b, x0, iterations = 50, tol = 0.000001, true = None):
    """
    Solves a system of linear equations using the Jacobi method
    Expected inputs:
    A: nxn matrix
    b: column vector of length n
    x0: initial guess for solution
    tol: error between true and numerical solution
    true: true solution
    """
    count = 0
    x = x0
    d = np.diagonal(A)
    LU = A - np.diag(d)
    n = np.size(b)
    if type(true) == np.ndarray:
        while max(abs(true - x)) > tol:
            count = count + 1
            x = (1/d)*(b - LU@x)
        print(f"Number of iterations = {count}")
        return(x)
    else:
        for i in range(iterations):
            x = (1/d)*(b - LU@x)
        return(x)


## When writing this code, we run into a few errors: 
Creating different scenarios for the method alorithm when we include the true solution in our input lead to some issues, and had to use the code "type(true) == np.ndarray" which was not clear at first. 

At first, John tried to use matrix multiplication when multiplying by d inverse (like is done in the mathmatical algoritm), however, d is stored as an array in our code and because of vectorized nature of numpy, the solution was to just use the normal multiplication operator.

## Testing the Algorithm

- Example from HW 3

In [2]:
L = np.diag(-np.ones(99), -1)
U = np.diag(-np.ones(99), 1)
d = np.diag(3*np.ones(100))
A = L + U + d
b = np.array([2] + [1]*98 + [2])
x = jacobi(A, b, np.zeros(100), tol = 0.000001, true = np.ones(100))
x


Number of iterations = 35


array([0.99999991, 0.99999982, 0.99999974, 0.99999966, 0.99999959,
       0.99999953, 0.99999948, 0.99999943, 0.9999994 , 0.99999937,
       0.99999936, 0.99999934, 0.99999933, 0.99999932, 0.99999932,
       0.99999932, 0.99999932, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999931,
       0.99999931, 0.99999931, 0.99999931, 0.99999931, 0.99999

## Algorithm written by Chat GPT 3.5:

In [3]:
def jacobi_GPT(A, b, x0, tol=1e-6, max_iter=1000):
    n = len(b)
    x = np.array(x0, dtype=float)
    x_new = np.zeros_like(x)
    
    for _ in range(max_iter):
        for i in range(n):
            sum_ = np.dot(A[i, :i], x[:i]) + np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - sum_) / A[i, i]
        
        if np.linalg.norm(x_new - x) < tol:
            return x_new
        
        x = np.copy(x_new)
    
    raise ValueError("Jacobi method did not converge within the maximum number of iterations")

- Chat gpts code stops the alorithm when the difference between the new value and the last value is less than a certain amount, which is different than our code which uses a set number of iterations (or requires the solution which is helpful for testing)

## Testing Chat GPT's code with the same example from HW 3

In [4]:
L = np.diag(-np.ones(99), -1)
U = np.diag(-np.ones(99), 1)
d = np.diag(3*np.ones(100))
A = L + U + d
b = np.array([2] + [1]*98 + [2])
x_GPT = jacobi_GPT(A, b, np.zeros(100), tol = 0.000001)
print(x_GPT)
print(max(abs(x_GPT - x)))

[0.99999997 0.99999995 0.99999992 0.9999999  0.99999988 0.99999987
 0.99999985 0.99999984 0.99999983 0.99999982 0.99999981 0.99999981
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.9999998  0.9999998
 0.9999998  0.9999998  0.9999998  0.9999998  0.99999981 0.99999981
 0.9999

The GPT 3.5 code produced a result extremely close to the result of our code. Asking Chat GPT to write the code took about 2 minutes, whereas the code we wrote took about an hour with trial and error being required.

In [5]:
A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
b = np.array([0, 2, 0])
x = jacobi(A, b, np.zeros(3))
print(x)
x_gpt = jacobi_GPT(A, b, np.zeros(3))
print(x_gpt)

[0.99999997 1.99999994 0.99999997]
[0.99999905 1.99999905 0.99999905]


Above is another example from HW 3

- Both of the functions produced results close to the true solution

# Gradient Descent Method By Zhenyuan Ni

In [7]:
import numpy as np


def gradient_descent(gradient, start, learn_rate, n_iterations, tolerance):
    vector = start
    for _ in range(n_iterations):
        diff = -learn_rate * gradient(vector)
        if np.all(np.abs(diff) <= tolerance):
            break
        vector += diff
    return vector


# Example usage
# Define the gradient of your function here
def gradient_function(v):
    # Example for a 2D function: f(x, y) = x^2 + y^2
    return np.array([2 * v[0], 2 * v[1]])


# Starting point (can be any point in your domain)
start_point = np.array([10.0, 10.0])

# Learning rate
learn_rate = 0.1

# Number of iterations
n_iterations = 1000

# Tolerance for stopping criterion
tolerance = 1e-6

minimum = gradient_descent(gradient_function, start_point, learn_rate, n_iterations, tolerance)
print("Minimum at:", minimum)


# Multivariable case
def func(v):
    return v[0]**2 - v[1] * v[2]**2 + v[2] * v[3] * v[4]**2


def gradient_function1(v):
    # Example for a 2D function: f(x, y) = x1^2 - x2 * x3^2 + x3 * x4 * x5^2
    return np.array([2 * v[0], -v[1], 2*v[2] + v[3] + v[4], v[2] + v[4], v[3] + v[4]])


start_point = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
minimum = gradient_descent(gradient_function1, start_point, learn_rate, n_iterations, tolerance)
print("Minimum at:", minimum)
ylist = []
for x1 in range(10):
    for x2 in range(10):
        for x3 in range(10):
            for x4 in range(10):
                for x5 in range(10):
                    ylist.append(func([1 + 0.1 * x1, 4 + 0.1 * x2, -6 + 0.1 * x3, 4 + 0.1 * x4, -2 + 0.1 * x5]))
miny = np.min(ylist) - func(minimum)
print(miny)


Minimum at: [4.01734511e-06 4.01734511e-06]
Minimum at: [ 1.23023192e-97  4.93986584e+41 -6.29828712e+29  4.07127679e+30
 -2.35055275e+30]
1.4167495700510191e+121


# Chatgpt 3.5 Gradient Descent method

Chat Gpt notes that a common optimization for better efficiency is to use vectorized coding instead:

- One common optimization is to use vectorized operations whenever possible to leverage the computational efficiency of NumPy. 
- Additionally, we can adjust the step size dynamically during optimization to improve convergence. 

Here's the optimized version of the code:

In [5]:
import numpy as np

def gradient_descent(gradient, start, learn_rate, n_iterations, tolerance):
    vector = start
    for _ in range(n_iterations):
        diff = -learn_rate * gradient(vector)
        if np.all(np.abs(diff) <= tolerance):
            break
        vector += diff
        # Adjust learning rate dynamically
        learn_rate *= 0.9  # or any other suitable decay factor
    return vector

# Example usage
# Define the gradient of your function here
def gradient_function(v):
    # Example for a 2D function: f(x, y) = x^2 + y^2
    return np.array([2 * v[0], 2 * v[1]])

# Starting point (can be any point in your domain)
start_point = np.array([10.0, 10.0])

# Learning rate
learn_rate = 0.1

# Number of iterations
n_iterations = 1000

# Tolerance for stopping criterion
tolerance = 1e-6

minimum = gradient_descent(gradient_function, start_point, learn_rate, n_iterations, tolerance)
print("Minimum at:", minimum)

# Multivariable case
def func(v):
    return v[0]**2 - v[1] * v[2]**2 + v[2] * v[3] * v[4]**2

def gradient_function1(v):
    # Gradient of the function f(v) = v[0]^2 - v[1] * v[2]^2 + v[2] * v[3] * v[4]^2
    grad = np.zeros_like(v)
    grad[0] = 2 * v[0]
    grad[1] = -v[2]**2
    grad[2] = -2 * v[1] * v[2] + v[3] * v[4]**2
    grad[3] = v[2] * v[4]**2
    grad[4] = 2 * v[2] * v[3] * v[4]
    return grad


start_point = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
minimum = gradient_descent(gradient_function1, start_point, learn_rate, n_iterations, tolerance)
print("Minimum at:", minimum)

# No need to search for minimum manually
# Minimum value can be calculated directly from the function
miny = func(minimum)
print(miny)


Minimum at: [1.20459505 1.20459505]
Minimum at: [0.12045854        nan        nan        nan        nan]
nan


/var/folders/xh/4xpwy9dj7glg3lpzyn0wwqgw0000gn/T/ipykernel_4675/1267282877.py:43: RuntimeWarning: overflow encountered in scalar power
  grad[1] = -v[2]**2
/var/folders/xh/4xpwy9dj7glg3lpzyn0wwqgw0000gn/T/ipykernel_4675/1267282877.py:44: RuntimeWarning: overflow encountered in scalar power
  grad[2] = -2 * v[1] * v[2] + v[3] * v[4]**2
/var/folders/xh/4xpwy9dj7glg3lpzyn0wwqgw0000gn/T/ipykernel_4675/1267282877.py:45: RuntimeWarning: overflow encountered in scalar power
  grad[3] = v[2] * v[4]**2
/var/folders/xh/4xpwy9dj7glg3lpzyn0wwqgw0000gn/T/ipykernel_4675/1267282877.py:46: RuntimeWarning: overflow encountered in scalar multiply
  grad[4] = 2 * v[2] * v[3] * v[4]
/var/folders/xh/4xpwy9dj7glg3lpzyn0wwqgw0000gn/T/ipykernel_4675/1267282877.py:44: RuntimeWarning: invalid value encountered in scalar add
  grad[2] = -2 * v[1] * v[2] + v[3] * v[4]**2
/var/folders/xh/4xpwy9dj7glg3lpzyn0wwqgw0000gn/T/ipykernel_4675/1267282877.py:9: RuntimeWarning: invalid value encountered in add
  vector += di

We see that there was an overflow issue with the results in the code. This is primarily due to:

- the gradient vector was properly updated, and for multivariate cases we see this is an issue that can arise for wrong initial guesses, 
- The need to change hyperparameters (learning rate, iterations etc.)

This can be explored more so in another course but this is very interesting to see what can cause runtime warnings 